### ISSUE TITLE
Money type

### ISSUE THREAD

**Issue by mlotysz** [rafek1241/Patronage-17-java#5]
Use consistent Java type for money. I see, that `PriceCategory.price` is an `int` but `User.balance` is `double`.
Bear in mind:
- http://stackoverflow.com/questions/8148684/what-is-the-best-data-type-to-use-for-money-in-java-app
- http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by rafek1241** [comment]
In last push - changed `double` and `int` to the `BigDecimal`
