### ISSUE TITLE
How to test your system?

### ISSUE THREAD

**Issue by mlotysz** [rafek1241/Patronage-17-java#7]
I miss some example usage in README. Write example `curl` commands, please.
Particularly I don't see how to:
- set price category on new movie
- how a user rent a movie
- how to prevent a user from altering rented movies (I see it could be updated by `POST` on `/users`. Am I right?)

**Comment by rafek1241** [comment]
@mlotysz 
- When we insert movie we set price category.
- User rent movie by POST method sending the list of movie ids.
- We can only rent each movies **once**. On Movie entity we have bool **rented** flag which is set on true when movie is rented. In `rentMovie()` we check if movie is rented and return false if it is.

**Comment by mlotysz** [comment]
Could you document them as `curl` commands? (Without ready to use `curl` commands or JUnit tests we cannot check your solution...)

**Comment by rafek1241** [comment]
I'll do it ASAP

**Comment by mlotysz** [comment]
Resolve this issue first - #2 and #6 are not important today.
